 const data = {
    data: {
      client_id: 'rc_lJzfqjwIGurdUcoTagaA',
      rc_number: 'TN07CX4416',
      fit_up_to: '2036-04-28',
      registration_date: '2021-04-29',
      owner_name: 'ELUMALAI M',
      father_name: '',
      present_address: 'NO 1-C TYPE IV CLRI STAFF QUARTERS, ADYAR, , Chennai, Tamil Nadu, 600020',
      permanent_address: 'NO 1-C TYPE IV CLRI STAFF QUARTERS, ADYAR, , Chennai, Tamil Nadu, 600020',
      mobile_number: '',
      vehicle_category: 'LMV',
      vehicle_chasi_number: 'MALBG512LMM066324',
      vehicle_engine_number: 'G4LFMV098202',
      maker_description: 'HYUNDAI MOTOR INDIA LTD',
      maker_model: 'I20 MAGNA 1.2 KAPPA MT',
      body_type: 'HATCHBACK',
      fuel_type: 'PETROL',
      color: 'FIERY RED',
      norms_type: 'BHARAT STAGE VI',
      financer: 'ICICI BANK LTD',
      financed: true,
      insurance_company: 'IFFCO Tokio General Insurance Co. Ltd.',
      insurance_policy_number: '56308773',
      insurance_upto: '2026-04-26',
      manufacturing_date: '4/2021',
      manufacturing_date_formatted: '2021-04',
      registered_at: 'CHENNAI (SOUTH) RTO, Tamil Nadu',
      latest_by: '2026-01-28',
      less_info: true,
      tax_upto: '2036-04-28',
      tax_paid_upto: '2036-04-28',
      cubic_capacity: '1197.00',
      vehicle_gross_weight: '1410',
      no_cylinders: '4',
      seat_capacity: '5',
      sleeper_capacity: '0',
      standing_capacity: '0',
      wheelbase: '2580',
      unladen_weight: '959',
      vehicle_category_description: 'Motor Car(LMV)',
      pucc_number: '',
      pucc_upto: null,
      permit_number: '0',
      permit_issue_date: null,
      permit_valid_from: null,
      permit_valid_upto: null,
      permit_type: '',
      national_permit_number: '',
      national_permit_upto: null,
      national_permit_issued_by: null,
      non_use_status: null,
      non_use_from: null,
      non_use_to: null,
      blacklist_status: '',
      noc_details: '',
      owner_number: '1',
      rc_status: 'ACTIVE',
      masked_name: false,
      challan_details: null,
      variant: null,
      rto_code: '',
      response_metadata: [Object]
    },
    status_code: 200,
    success: true,
    message: null,
    message_code: 'success'
  }