const data =  {
    client_id: 'rc_kNrHXoQZeFccudmfppif',
    rc_number: 'MH20DV2366',
    fit_up_to: '2031-02-25',
    registration_date: '2016-02-26',
    owner_name: 'SARANG  CHOUDHARY',
    father_name: '',
    present_address: 'P NO 03.LEELASHANKAR PAGARIYA, COLONY STATION ROAD, OPP, GOLDIE CINEMA AURANGABAD, Chhatrapati Sambhajinagar, Maharashtra,',
    permanent_address: 'P NO 03.LEELASHANKAR PAGARIYA, COLONY STATION ROAD, OPP, GOLDIE CINEMA AURANGABAD, Chhatrapati Sambhajinagar, Maharashtra,',
    mobile_number: '',
    vehicle_category: 'LMV',
    vehicle_chasi_number: 'TMBBKJNP6FA310011',
    vehicle_engine_number: 'CRG000518',
    maker_description: 'SKODA AUTO INDIA PVT LTD',
    maker_model: 'SUPERB L & K 2.0 TDI AT',       
    body_type: 'SALOON',
    fuel_type: 'DIESEL',
    color: 'B SILVER',
    norms_type: 'Not Available',
    financer: '',
    financed: false,
    insurance_company: 'The New India Assurance Company Limited',
    insurance_policy_number: '16040031240100014552',
    insurance_upto: '2026-02-19',
    manufacturing_date: '10/2015',
    manufacturing_date_formatted: '2015-10',      
    registered_at: 'CHHATRAPATI SAMBHAJINAGAR, Maharashtra',
    latest_by: '2026-02-06',
    less_info: true,
    tax_upto: '2031-02-25',
    tax_paid_upto: '2031-02-25',
    cubic_capacity: '1968.00',
    vehicle_gross_weight: '2060',
    no_cylinders: '4',
    seat_capacity: '5',
    sleeper_capacity: null,
    standing_capacity: null,
    wheelbase: null,
    unladen_weight: '1565',
    vehicle_category_description: 'Motor Car(LMV)',
    pucc_number: 'MH02000090026033',
    pucc_upto: '2025-01-21',
    permit_number: '',
    permit_issue_date: null,
    permit_valid_from: null,
    permit_valid_upto: null,
    permit_type: '',
    national_permit_number: '',
    national_permit_upto: null,
    national_permit_issued_by: null,
    non_use_status: null,
    non_use_from: null,
    non_use_to: null,
    blacklist_status: '',
    noc_details: '',
    owner_number: '2',
    rc_status: 'ACTIVE',
    masked_name: false,
    challan_details: null,
    variant: null,
    rto_code: '',
    response_metadata: {
      masked_chassis: false,
      masked_engine: false,
      masked_owner_name: false
    }
}       